# if (condition):
#   ...                                                 Spaces(Indentation) are automatically given
#   ...                                                 to understand the statements of "if condition"  
#   Code
#   ...
#   ...


# else:
#   ...
#   ...
#   Code
#   ...
#   ...